name: 'Install, Lint, Unit test, Build'

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: cache
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      # Should be fast with the yarn cache restored
      - run: yarn install --frozen-lockfile --check-files

      # Cache the entire working directory for subsequent steps
      - uses: actions/cache@v1
        with:
          path: '.'
          key: ${{ github.sha }}

  codeLinter:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v1
        with:
          path: '.'
          key: ${{ github.sha }}

      - run: yarn lint
      - run: yarn check-format

  jestUnitTests:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v1
        with:
          path: '.'
          key: ${{ github.sha }}

      - run: yarn jest
        env:
          CI: true

  cypress:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v1
        with:
          path: '.'
          key: ${{ github.sha }}

      - uses: actions/cache@v1
        id: cypress-cache
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ hashFiles('**/yarn.lock') }}

      - if: steps.cypress-cache.outputs.cache-hit != 'true'
        run: yarn run cypress install

      # Build the next.js app
      - run: yarn build
        env:
          API_URL: ${{ secrets.API_URL }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}

      - uses: cypress-io/github-action@v1
        with:
          env: ${{ secrets.CYPRESS_GITHUB_ENV }}
          install: false
          start: yarn start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60

      - uses: actions/upload-artifact@v1
        with:
          name: cypress-screenshots
          path: cypress/screenshots
