name: 'Install, lint, unit test, build, run Cypress tests'

on: [pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: actions/checkout@v2

      # Install and cache the build
      - uses: bahmutov/npm-install@v1
        env:
          # Setting to 0 skips installing the binary
          CYPRESS_INSTALL_BINARY: 0

      # Cache the entire working directory for subsequent steps
      - uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.sha }}

  typeCheck:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.sha }}

      - run: yarn tsc

  codeLinter:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.sha }}

      - run: yarn lint
      - run: yarn check-format

  jestUnitTests:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.sha }}

      - run: yarn jest
        env:
          CI: true

  # Keep separate from
  nextjsBuild:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.sha }}

      # Cache the next.js cache folder per os/dependency change
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-cache-${{ hashFiles('**/yarn.lock') }}

      - run: yarn build
        env:
          NEXT_PUBLIC_BASEMAP_DISABLED: true
          NEXT_PUBLIC_CYPRESS: true
          NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}

      # Cache entire .next folder for subsequent steps
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next
          key: ${{ runner.os }}-${{ github.sha }}-nextjs

  cypressIntegration:
    needs: [codeLinter, jestUnitTests, nextjsBuild, typeCheck] # only run if these all pass
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
    strategy:
      matrix:
        backend: [dev-latest] # keep as a matrix strategy to test against an additional specific build later

    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      # Install / cache dependencies with Cypress to handle caching Cypress binary.
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          # just perform install
          runTests: false

      # Restore entire .next folder from previous step
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next
          key: ${{ runner.os }}-${{ github.sha }}-nextjs

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Download Analysis Backend
        run: curl https://r5-builds.s3-eu-west-1.amazonaws.com/${{ matrix.backend }}.jar --output ${{ github.workspace }}/${{ matrix.backend }}.jar

      - name: Cache Cypress
        id: cache-cypress
        uses: actions/cache@v1
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-v2-${{ runner.os }}-${{ hashFiles('**/package.json') }}
      # Install Cypress binary
      - run: npx cypress install

      - uses: cypress-io/github-action@v2
        with:
          install: false
          start: yarn start, yarn start-backend # runs frontend and java server together
          wait-on: 'http://localhost:3000, http://localhost:7070/version'
          wait-on-timeout: 60

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
