name: Build, Test, Deploy

on: [pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile --check-files

      - uses: actions/cache@v1
        id: cache-build
        with:
          path: '.'
          key: ${{ github.sha }}

  codeLinter:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v1
        id: restore-build
        with:
          path: '.'
          key: ${{ github.sha }}

      - run: yarn lint
      - run: yarn check-format

  jestUnitTests:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v1
        id: restore-build
        with:
          path: '.'
          key: ${{ github.sha }}

      - run: yarn jest
        env:
          CI: true

  cypress:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v1
        id: restore-build
        with:
          path: '.'
          key: ${{ github.sha }}

      # Install the binary
      - run: yarn run cypress install

      # Build then run the next.js server in the background
      - run: |
          yarn build
          yarn start &
        env:
          API_URL: ${{ secrets.API_URL }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}

      - uses: cypress-io/github-action@v1
        with:
          install: false
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60
          env: ${{ secrets.CYPRESS_GITHUB_ENV }}

      - uses: actions/upload-artifact@v1
        with:
          name: cypress-screenshots
          path: cypress/screenshots
